version: '3.9'

services:
  syncer:
    image: warpredstone/syncer:latest
    profiles:
      - syncer
    command: [ "/app/bin/syncer", "sync" ]
    depends_on:
      - db
    healthcheck:
      test: curl --fail http://localhost:3333/v1/health || exit 1
      interval: 5s
      timeout: 10s
      retries: 1
      start_period: 40s
    environment:
      SYNCER_DBPORT: 5432
      SYNCER_DBHOST: db
      SYNCER_DBUSER: postgres
      SYNCER_DBPASSWORD: postgres
      SYNCER_DBNAME: warp
      SYNCER_DBSSLMODE: disable
      SYNCER_DBPINGTIMEOUT: 10s
      SYNCER_RESTLISTENADDRESS: :3333
      SYNCER_LOGLEVEL: debug
      SYNCER_ARNODEURL: https://arweave.net
      SYNCER_ARSTABLEDISTANCE: 10
      SYNCER_LISTENERQUEUESIZE: 10
      SYNCER_STOREBATCHSIZE: 1000
      SYNCER_STOREMAXTIMEINQUEUE: 2m
      SYNCER_STOREMAXTIMEBETWEENRECONNECTS: 5s

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - syncer_db_volume:/var/lib/postgresql/data
    ports:
      - 7654:5432
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: warp

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    network_mode: host
    depends_on:
      - db
    environment:
      - PGADMIN_LISTEN_PORT=5151
      - PGADMIN_DEFAULT_EMAIL=admin@warp.cc
      - PGADMIN_DEFAULT_PASSWORD=password
      - MAX_LOGIN_ATTEMPTS=10000

volumes:
  syncer_db_volume: null
