version: '3.2'

services:
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - syncer_db_volume:/var/lib/postgresql/data
    ports:
      - 7654:5432
    command: [ "postgres", "-c", "log_statement=all" ]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: warp

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    network_mode: host
    depends_on:
      - db
    environment:
      - PGADMIN_LISTEN_PORT=5151
      - PGADMIN_DEFAULT_EMAIL=admin@warp.cc
      - PGADMIN_DEFAULT_PASSWORD=password


volumes:
  syncer_db_volume: null
